// Generated by https://quicktype.io

export interface MetricasData {
  datos: Dato[];
}

export interface Dato {
  mes: number;
  year: number;
  sesiones: number;
  usuarios_analytics: number;
  duracion_media: number;
  rebote: number;
  nuevas_sesiones: number;
}
